version: 2
jobs:
  build:
    docker:
      - image: uochan/vim:latest
    working_directory: /tmp/workspace
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip3 install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          command: |
            . venv/bin/activate
            bash scripts/lint.sh
            python3 -m doctest python/bencode.py
      - run:
          command: |
            git clone https://github.com/thinca/vim-themis .vim-themis
            git clone https://github.com/guns/vim-sexp .vim-sexp
            ./.vim-themis/bin/themis
      - run:
          command: |
            . venv/bin/activate
            bash scripts/coverage.sh
  ancient:
    docker:
      - image: circleci/clojure:tools-deps
    working_directory: /tmp/workspace
    steps:
      - checkout
      - restore_cache:
          keys:
          - v2-dependencies-{{ checksum "deps.edn" }}
      - run:
          command: |
            bash scripts/ancient.sh
      - save_cache:
          paths:
            - ~/.clojure/.cpcache
            - ~/.m2
          key: v2-dependencies-{{ checksum "deps.edn" }}

workflows:
  version: 2
  all_test:
    jobs:
      - build
#      - ancient
