version: 2
jobs:
  lint:
    docker:
      - image: circleci/python:3.6.1
    working_directory: /tmp/workspace
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          command: |
            . venv/bin/activate
            find . -name "*.vim" | grep -v vital | grep -v .vim-themis | grep -v .vim-sexp | xargs vint
  test:
    docker:
      - image: thinca/themis
    working_directory: /tmp/workspace
    steps:
      - checkout
      - run:
          command: |
            git clone https://github.com/guns/vim-sexp .vim-sexp
            vim --version
            themis --runtimepath ./.vim-sexp --runtimepath ./test/helper
workflows:
  version: 2
  all_test:
    jobs:
      - lint
      - test
