version: 2
jobs:
  build:
    docker:
      - image: thinca/vim:latest-full
    working_directory: /tmp/workspace
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            apk add --no-cache bash curl git
            python3 -m venv venv
            . venv/bin/activate
            pip3 install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          command: |
            . venv/bin/activate
            bash scripts/lint.sh
            python3 -m doctest python/bencode.py
      - run:
          command: |
            git clone https://github.com/thinca/vim-themis .vim-themis
            git clone https://github.com/guns/vim-sexp .vim-sexp
            ./.vim-themis/bin/themis
      - run:
          command: |
            . venv/bin/activate
            bash scripts/coverage.sh
