name: neovim
on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev
jobs:
  themis:
    runs-on: ubuntu-latest
    container:
      image: lambdalisue/neovim-themis:latest
    steps:
      - uses: actions/checkout@v1
      - name: install git
        run: apk update && apk upgrade && apk add --no-cache git
      - name: clone vim-sexp
        run: git clone --depth 1 --single-branch https://github.com/guns/vim-sexp .vim-sexp
      - name: run themis
        run: /opt/github.com/thinca/vim-themis/bin/themis
