name: vim
on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: uochan/vim:latest
    steps:
      - uses: actions/checkout@v1
      - name: cache venv
        uses: actions/cache@v1
        with:
          path: ./venv
          key: vim-venv-${{ hashFiles('requirements.txt') }}
      - name: pip install
        run: python3 -m venv venv && . venv/bin/activate && pip3 install -r requirements.txt
      - name: vint
        run: . venv/bin/activate && bash scripts/lint.sh
      - name: python doctest
        run: . venv/bin/activate && python3 -m doctest python/bencode.py
      - name: clone themis
        run: git clone --depth 1 --single-branch https://github.com/thinca/vim-themis .vim-themis
      - name: clone vim-sexp
        run: git clone --depth 1 --single-branch https://github.com/guns/vim-sexp .vim-sexp
      - name: run themis
        run: ./.vim-themis/bin/themis
      - name: coverage
        run: . venv/bin/activate && bash scripts/coverage.sh
